"""
Sindlish Language Interpreter — CLI Entry Point.

This script provides a command-line interface for the Sindlish programming language,
allowing users to run files, start an interactive REPL, evaluate code strings,
and inspect the internal representation (tokens, AST) for debugging purposes.
"""

import argparse
import sys
import time
import os
import tomllib
from pathlib import Path
from interpreter import Interpreter
from interpreter.repl import start_repl
from interpreter.frontend.lexer import Lexer
from interpreter.frontend.parser import Parser
from interpreter.errors import SindhiBaseError

def get_version():
    """Retrieve version from pyproject.toml."""
    try:
        # Try reading from pyproject.toml directly for local development
        root_dir = Path(__file__).parent
        pyproject_path = root_dir / "pyproject.toml"
        if pyproject_path.exists():
            with open(pyproject_path, "rb") as f:
                data = tomllib.load(f)
                return data.get("project", {}).get("version", "unknown")
        
        # Fallback to importlib.metadata if installed as a package
        from importlib.metadata import version, PackageNotFoundError
        try:
            return version("sindlish")
        except PackageNotFoundError:
            return "0.1.0"
    except Exception:
        return "0.1.0"

VERSION = get_version()

def run_tokens(code):
    """Print the tokens generated by the lexer."""
    try:
        lexer = Lexer(code)
        tokens = lexer.generate_tokens()
        for token in tokens:
            print(token)
    except SindhiBaseError as e:
        print(f"Lexer Error: {e}")
        sys.exit(1)

def run_ast(code):
    """Print the Abstract Syntax Tree generated by the parser."""
    try:
        lexer = Lexer(code)
        tokens = lexer.generate_tokens()
        parser = Parser(tokens, code)
        ast = parser.parse()
        print(ast)
    except SindhiBaseError as e:
        print(f"Parser Error: {e}")
        sys.exit(1)

def run_file(file_path, show_time=False):
    """Execute a Sindlish (.sd) file."""
    if not file_path.endswith(".sd"):
        print(f"Error: File '{file_path}' must have .sd extension.")
        sys.exit(1)
    
    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            code = f.read()
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    interp = Interpreter()
    
    start = time.perf_counter()
    try:
        interp.run_source(code)
    except SindhiBaseError:
        # Interpreter already reports the error
        sys.exit(1)
    except Exception as e:
        print(f"Internal Error: {e}")
        sys.exit(1)
    end = time.perf_counter()
    
    if show_time:
        print(f"\n[Execution time: {end - start:.4f}s]")

def run_eval(code, show_time=False):
    """Evaluate a string of Sindlish code."""
    interp = Interpreter()
    start = time.perf_counter()
    try:
        interp.run_source(code)
    except SindhiBaseError:
        sys.exit(1)
    except Exception as e:
        print(f"Internal Error: {e}")
        sys.exit(1)
    end = time.perf_counter()
    
    if show_time:
        print(f"\n[Execution time: {end - start:.4f}s]")

def check_file(file_path):
    """Check a file for syntax and resolution errors without executing it."""
    # Note: Currently the Interpreter doesn't have a check-only mode that skips VM execution easily.
    # We'll just run Lexer and Parser for now.
    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            code = f.read()
        
        lexer = Lexer(code)
        tokens = lexer.generate_tokens()
        parser = Parser(tokens, code)
        parser.parse()
        print(f"OK: '{file_path}' passed syntax check.")
    except SindhiBaseError as e:
        print(f"Check Failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Internal Error during check: {e}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(
        prog="sindlish",
        description="Sindlish Language Interpreter - A localized high-level programming language.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  sindlish run script.sd       # Run a file
  sindlish repl                # Start interactive shell
  sindlish eval "likh(1+2)"    # Evaluate code directly
  sindlish tokens script.sd    # View lexer tokens
  sindlish ast script.sd       # View parser AST
"""
    )
    
    parser.add_argument(
        "-v", "--version", 
        action="version", 
        version=f"Sindlish Interpreter {VERSION}"
    )

    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # Run command
    run_parser = subparsers.add_parser("run", help="Run a Sindlish (.sd) file")
    run_parser.add_argument("file", help="Path to the .sd file")
    run_parser.add_argument("-t", "--time", action="store_true", help="Show execution time")

    # REPL command
    subparsers.add_parser("repl", help="Start the interactive REPL")

    # Eval command
    eval_parser = subparsers.add_parser("eval", help="Evaluate Sindlish code string")
    eval_parser.add_argument("code", help="Sindlish code to evaluate")
    eval_parser.add_argument("-t", "--time", action="store_true", help="Show execution time")

    # Tokens command
    tokens_parser = subparsers.add_parser("tokens", help="Show tokens for a file")
    tokens_parser.add_argument("file", help="Path to the .sd file")

    # AST command
    ast_parser = subparsers.add_parser("ast", help="Show AST for a file")
    ast_parser.add_argument("file", help="Path to the .sd file")

    # Check command
    check_parser = subparsers.add_parser("check", help="Check file for syntax errors")
    check_parser.add_argument("file", help="Path to the .sd file")

    # Handle legacy behavior and defaults
    if len(sys.argv) == 1:
        # No arguments: start REPL
        start_repl(VERSION)
        return

    # If first arg is a file ending in .sd, assume 'run'
    if not sys.argv[1].startswith("-") and sys.argv[1] not in subparsers.choices:
        if sys.argv[1].endswith(".sd"):
            sys.argv.insert(1, "run")
        else:
            # Maybe it's a file but without .sd, let 'run' handle the error
            # Or if it's not a command, it's invalid unless we want it to default to REPL?
            # Let's keep it strict for better CLI design.
            pass

    args = parser.parse_args()

    if args.command == "run":
        run_file(args.file, args.time)
    elif args.command == "repl":
        start_repl(VERSION)
    elif args.command == "eval":
        run_eval(args.code, args.time)
    elif args.command == "tokens":
        with open(args.file, "r", encoding="utf-8") as f:
            run_tokens(f.read())
    elif args.command == "ast":
        with open(args.file, "r", encoding="utf-8") as f:
            run_ast(f.read())
    elif args.command == "check":
        check_file(args.file)
    else:
        # If somehow we get here without a command, start REPL
        start_repl(VERSION)

if __name__ == "__main__":
    main()
