import json
import re
import sys
import os
import difflib
import argparse

def throw_ghalti(line_no, token, suggestion=None):
    """Prints a high-visibility error message and kills the process."""
    print("\n" + "="*50)
    print(f"  [SINDLISH GHALTI] - LINE {line_no}")
    print(f"  Unknown token found: '{token}'")
    if suggestion:
        print(f"  Did you mean:        '{suggestion}'?")
    print("="*50)
    print("Transpilation aborted. Fix the error to continue.\n")
    sys.exit(1)

def load_dictionary(path):
    if not os.path.exists(path):
        print(f"Error: {path} not found. Please ensure your dictionary is in the folder.")
        sys.exit(1)
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    # Mapping: Sindlish -> Python
    return {v: k for k, v in data.items()}

def transpile(source, mapping):
    lines = source.splitlines()
    final_code = []
    keywords = set(mapping.keys())
    
    # Pre-sort keywords by length (longest first) to prevent partial matches
    sorted_keywords = sorted(mapping.keys(), key=len, reverse=True)

    for i, line in enumerate(lines, 1):
        if not line.strip():
            final_code.append("")
            continue

        # 1. MASK STRINGS: Protect text inside "..." or '...'
        # We replace them with a placeholder so we don't 'correct' user text.
        original_strings = re.findall(r'(\".*?\"|\'.*?\')', line)
        temp_line = re.sub(r'(\".*?\"|\'.*?\')', " __SIND_STR__ ", line)

        # 2. STRICT TOKEN CHECK
        # We find every 'word' in the code logic.
        tokens = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', temp_line)
        
        for token in tokens:
            if token == "__SIND_STR__": continue
            
            # If the word is NOT a keyword, check if it's a typo of one.
            if token not in keywords:
                # 0.7 cutoff is strict enough to catch 'ager' but ignore unique variables
                matches = difflib.get_close_matches(token, keywords, n=1, cutoff=0.7)
                if matches:
                    throw_ghalti(i, token, matches[0])

        # 3. TRANSPILE
        # Replace Sindlish with Python only for whole words
        for sind_word in sorted_keywords:
            py_word = mapping[sind_word]
            pattern = r'\b' + re.escape(sind_word) + r'\b'
            temp_line = re.sub(pattern, py_word, temp_line)

        # 4. UNMASK STRINGS: Put the user's original text back
        for s in original_strings:
            temp_line = temp_line.replace(" __SIND_STR__ ", s, 1)
        
        final_code.append(temp_line)

    return "\n".join(final_code)

def main():
    parser = argparse.ArgumentParser(description="Strict Sindlish to Python Transpiler")
    parser.add_argument("input", help="The .sind file to process")
    parser.add_argument("-d", "--dict", default="dictionary.json", help="Path to dictionary.json")
    args = parser.parse_args()

    # Setup
    sind_to_py = load_dictionary(args.dict)
    
    if not args.input.endswith(".sind"):
        print("Error: Input file must have a .sind extension.")
        return

    # Read
    with open(args.input, 'r', encoding='utf-8') as f:
        source_content = f.read()

    # Execute Transpilation
    translated_python = transpile(source_content, sind_to_py)

    # Save
    # output_path = args.input.replace(".sind", ".py")
    # with open(output_path, 'w', encoding='utf-8') as f:
    #     f.write("# Generated by Sindlish\n")
    #     f.write(translated_python)
    
    compiled = compile(translated_python, "<string>", "exec")
    exec(compiled, globals())
    
    # print(f"Transpilation successful: {output_path}")

if __name__ == "__main__":
    main()